apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: pie
  name: manual
spec:
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/Avtandilko/prom-interfaces-exporter
    contextDir: /
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: pie:latest
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile