kind: DeploymentConfig
apiVersion: v1
metadata:
  name: pie
spec:
  template: 
    metadata:
      labels:
        name: pie
    spec:
      containers:
        - name: pie
          image: pie
          ports:
            - containerPort: 9425
              protocol: TCP
  replicas: 2
  triggers:
    - type: 'ConfigChange'
    - type: 'ImageChange'
      imageChangeParams:
        automatic: true
        containerNames:
          - 'pie'
        from:
          kind: 'ImageStreamTag'
          name: 'pie:latest'
          namespace: dev
  strategy: 
    type: 'Rolling'
  paused: false 
  revisionHistoryLimit: 2 
  minReadySeconds: 0 